### ISSUE TITLE
Error on running the Example

### ISSUE THREAD

**Issue by arpu** [gkjohnson/threejs-octree#7]
Hello,

testing this octree implementation and have some problem with Example

``Uncaught SyntaxError: Cannot use import statement outside a module``

**Comment by gkjohnson** [comment]
You must run `npm install` and run `npm start` in order to build the example using parcel. It will not just work in a browser.

That aside this project is definitely unfinished and unmaintained. I was experimenting with Octrees years ago to see if it would give performance benefits for raycasting but there's not really a significant improvement when spatially indexing objects until you have a massive amount of objects (with this implementation, at least). It was one of my first attempts at implementing an optimization structure like this in JS. By all means take a look but I can't make promises as to the code quality 😁 I honestly barely remember where I left this project.
